"""Add likes table

Revision ID: 339bd1f1b8eb
Revises: 2b31236febcc
Create Date: 2024-09-12 11:29:14.327525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339bd1f1b8eb'
down_revision = '2b31236febcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tweet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
